add echo

diff --git a/.github/workflows/lint-check.yml b/.github/workflows/lint-check.yml
--- a/.github/workflows/lint-check.yml
+++ b/.github/workflows/lint-check.yml
@@ -24,3 +24,9 @@ jobs:
 
       - name: Run lint and format check
         run: yarn lint-and-format
+
+      - name: Check lint and format results
+        run: |
+          if [ ${{ job.status }} == 'failure' ]; then
+            echo "Lint and format check failed. Please address the issues before resubmitting the pull request."
+            exit 1
